# Generated by Django 5.0.6 on 2024-08-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_bill_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='total_Bill',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
