# Generated by Django 5.0.6 on 2024-08-12 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_stockbill'),
    ]

    operations = [
        migrations.AddField(
            model_name='productstock',
            name='stock_bill',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.stockbill'),
        ),
    ]
