# Generated by Django 5.0.6 on 2024-08-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productstock_stock_bill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockbill',
            name='supplier',
        ),
        migrations.AddField(
            model_name='stockbill',
            name='discount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
