# Generated by Django 5.0.6 on 2024-08-17 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='quantity',
        ),
    ]
