# Generated by Django 5.0.6 on 2024-08-17 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_asset_quantity_addcash'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('ADD', 'Add Money'), ('WITHDRAW', 'Withdraw Money'), ('EXPENSE', 'Expense'), ('SALARY', 'Salary'), ('BILLS', 'Other Bills')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField()),
                ('date', models.DateTimeField()),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.bank')),
            ],
        ),
        migrations.DeleteModel(
            name='AddCash',
        ),
    ]
